# Generated by Django 6.0.5 on 2026-06-01 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название сделки')),
                ('stage', models.CharField(choices=[('lead', 'Лид'), ('negotiation', 'Переговоры'), ('proposal', 'Коммерческое предложение'), ('approval', 'Согласование'), ('won', 'Победа'), ('lost', 'Проигрыш')], default='lead', max_length=20, verbose_name='Этап')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сумма, руб.')),
                ('probability', models.IntegerField(default=10, verbose_name='Вероятность, %')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='Ожидаемая дата закрытия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='clients.client', verbose_name='Клиент')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stage'], name='deals_deal_stage_f562ff_idx'), models.Index(fields=['manager'], name='deals_deal_manager_79a960_idx')],
            },
        ),
    ]
